<footer id="footer">
		<div class="container">
			<div class="footer">
				<div class="arr">
					<p>Lorem ipsum dolor sit amet,<br> consectetur adipisicing elit. Soluta, doloremque!</p>
				</div>
				<div class="h-foot">
					<p>Pegac NYU</p>
					<p>Робота в Європі</p>
				</div>
				<div class="phones-foot">
					<p>+38(068)1702304</p>
					<p>+38(066)2568545</p>
					<p>+38(063)4276069</p>
				</div>
			</div>
		</div>
	</footer>


</body>
</html>