<header id="header">
		<div class="container">
			<div class="header">
				<div class="logo">
					<img src="/img/logo pegac.png" alt="horse">
				</div>
				<div class="content">
					<div class="phones">
						<p>+38(068)1702304</p>
						<p>+38(066)2568545</p>
						<p>+38(063)4276069</p>
						<button class="btn">Зворотній<br>дзвінок менеджера</button>
					</div>
					<div class="menu">
						<ul>
							<a href="/"><li><span>Г</span>оловна</li></a>
							<a href="#"><li><span>В</span>акансії</li></a>
							<a href="#"><li><span>К</span>онтакти</li></a>
							<a href="/page/about.phtml"><li><span>П</span>ро нас</li></a>
							<a href="#"><li><span>В</span>ідгуки</li></a>
						</ul>
					</div>
				</div>
			</div>
			</div>
	</header>