<? include $_SERVER['DOCUMENT_ROOT'] . "/layout/head.phtml"?>

<? include $_SERVER['DOCUMENT_ROOT'] . "/layout/header.phtml"?>

	<section id="about">
		<div class="container">
			<div class="row">
				<div class="col-12 title">
					<h1>Про нас</h1>
					<h2>забезпечуємо гідне працевлаштування</h2>
					<button class="btn btn-about">Обрати вакансію</button>
				</div>
			</div>
		</div>
	</section>

	<section id="pegac">
		<div class="container">
			<div class="row">
				<div class="col-md-6 pegac">
					<img src="/img/logo pegac.png" alt="horse">
				</div>
				<div class="col-md-10 main-text">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia labore inventore doloremque incidunt placeat fugiat dolores temporibus animi harum id ea vitae possimus obcaecati reprehenderit laboriosam aut ut aliquam, nostrum porro eligendi laborum repellendus deleniti! Facere atque dolorum commodi officia, dolores ad non quod, cupiditate molestias a aperiam minus error distinctio ratione dolor, dolore soluta iste vitae autem! Earum dolorem excepturi maxime, perferendis nulla hic nam accusantium omnis. Porro voluptatibus quos, neque doloremque voluptatum harum quam sit fugit. Architecto vero neque eos a, beatae ad cum libero quaerat nesciunt velit quisquam magni id iste ex consequatur numquam, reiciendis iusto dolor.</p>
				</div>
			</div>
		</div>
	</section>

	<section id="why">
		<div class="container">
			<div class="row">
				<div class="col-12 why-h">
					<h2>Чому Pegac NYU?</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-4 why-item">
					<img src="/img/string 1.png" alt="">
					<p>Якість надання послуг</p>
				</div>
				<div class="col-md-4 why-item">
					<img src="/img/string 3.png" alt="">
					<p>Гідний рівень організації</p>
				</div>
				</div>
				<div class="row justify-content-center">
				<div class="col-md-4 why-item">
					<img src="/img/string 2.png" alt="">
					<p>Великий досвід роботи</p>
				</div>
				<div class="col-md-4 why-item">
					<img src="/img/string 4.png" alt="">
					<p>Безліч позитивних відгуків</p>
				</div>
			</div>
			</div>
		</div>
	</section>

<? include $_SERVER['DOCUMENT_ROOT'] . "/layout/footer.phtml"?>