<section id="main">
		<div class="container">
			<div class="row">
				<div class="col-12 title">
					<h1>Робота в Євпропі</h1>
					<h2>надійний партнер в сфері працевлаштування</h2>
					<button class="btn btn-main">Зворотній<br> дзвінок менеджера</button>
				</div>
			</div>
		</div>
</section>

<section id="about-work">
	<div class="container">
		<div class="row">
			<div class="col-12 about-work">
				<h2>Про роботу в Європі</h2>
			</div>
		</div>
		<div class="row justify-content-center">
			<div class="col-10 about-work-content">
				<img src="/img/man.png" alt="man">
				<p>робота по біометрії, тимчасового працевлаштування, за робочими візами інших країн</p>
			</div>
			<div class="col-10 about-work-content">
				<img src="/img/doc.png" alt="doc">
				<p>робота за прямим контрактом з підприємством і оформленням ВНЖ</p>
			</div>
			<div class="worker">
				<div class="work-but">
					<button class="btn btn-about btn-about-main">Подати заявку</button>
				</div>
				<img src="/img/worker.png" alt="worker">
			</div>
		</div>
	</div>
</section>

<section id="vac">
	<div class="container">
		<div class="row">
			<div class="col-12 voc-title">
				<h1>Вакансії</h1>
			</div>
		</div>
		<div class="voc-flex">
			<div class="vac-container">
				<div class="vac-item">
					<div class="voc-head">
						<img src="/img/vac1.jpg" alt="1">
						<div class="voc-head-title">
							<h4>Вакансія №1</h4>
						</div>
					</div>
					<div class="slide">
						<h3>Коротко про роботу</h3>
						<img src="/img/ar-down.png" alt="arrow">
					</div>
					<button class="btn btn-voc">Детальніше про роботу</button>
				</div>
			</div>
				<div class="vac-container">
					<div class="vac-item">
						<div class="voc-head">
							<img src="/img/vac2.png" alt="2">
							<div class="voc-head-title">
							<h4>Вакансія №2</h4>
						</div>
						</div>
						<div class="slide">
							<h3>Коротко про роботу</h3>
							<img src="/img/ar-down.png" alt="arrow">
						</div>
						<button class="btn btn-voc">Детальніше про роботу</button>
					</div>
				</div>
			<div class="vac-container">
				<div class="vac-item">
					<div class="voc-head">
						<img src="/img/vac2.png" alt="3">
						<div class="voc-head-title">
							<h4>Вакансія №3</h4>
						</div>
					</div>
					<div class="slide">
						<h3>Коротко про роботу</h3>
						<img src="/img/ar-down.png" alt="arrow">
					</div>
					<button class="btn btn-voc">Детальніше про роботу</button>
				</div>
			</div>
			<div class="vac-container">
				<div class="vac-item">
					<div class="voc-head">
						<img src="/img/vac2.png" alt="3">
						<div class="voc-head-title">
							<h4>Вакансія №3</h4>
						</div>
					</div>
					<div class="slide">
						<h3>Коротко про роботу</h3>
						<img src="/img/ar-down.png" alt="arrow">
					</div>
					<button class="btn btn-voc">Детальніше про роботу</button>
				</div>
			</div>
			<div class="vac-container">
				<div class="vac-item">
					<div class="voc-head">
						<img src="/img/vac2.png" alt="3">
						<div class="voc-head-title">
							<h4>Вакансія №3</h4>
						</div>
					</div>
					<div class="slide">
						<h3>Коротко про роботу</h3>
						<img src="/img/ar-down.png" alt="arrow">
					</div>
					<button class="btn btn-voc">Детальніше про роботу</button>
				</div>
			</div>
		</div>
	</div>
</section>